# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: MyNotebook


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'VSE-test(5758ce4c-958e-4101-825d-2996626b487f)'
    subscriptionId: '5758ce4c-958e-4101-825d-2996626b487f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-MyFirstProject'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/MarekSii/BasicVM/main/basicvm.json'
    deploymentMode: 'Incremental'